name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_docker_image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image for dummy-api
      run: docker build -t dummy-api:latest ./dummy-api

    - name: Run Docker container for dummy-api
      run: docker run -d --name dummy-api -p 3001:3001 dummy-api:latest

  node_js_setup_and_tests:
    runs-on: ubuntu-latest
    needs: build_docker_image

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install
      working-directory: ./src

    - name: Run tests
      run: npm test
      working-directory: ./src

  build_and_deploy:
    runs-on: ubuntu-latest
    needs: node_js_setup_and_tests

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install
      working-directory: ./src

    - name: Build project
      run: npm run build
      working-directory: ./src

    - name: Deploy to Firebase Hosting
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
        channelId: live
        projectId: webdev2riis
